### ISSUE TITLE
Fix issue with starting rotation logic based on direction vector

### ISSUE THREAD

**Issue by rgarmsen2295** [joncatanio/GrannyGauntlet#15]
Porting to glm caused an issue with the current "rotate object to direction vector" logic.

**Comment by joncatanio** [comment]
I think this has to do with the rotations function in `MatrixStack.cpp` expecting radians. In the code where we actually pull out the angle from the dot product for the objects it looks like we are doing a hasty conversion to degrees.

**Comment by rgarmsen2295** [comment]
Yeah, I think Eigen was the reverse then, I'll take a look tonight as well, but if you've got a working solution go ahead and push it. Thanks!
