### ISSUE TITLE
Literal blue screen issue occasionally on lauch

### ISSUE THREAD

**Issue by rgarmsen2295** [joncatanio/GrannyGauntlet#17]
Occassionally the player is left staring into the blue (glBackgroundClr) abyss.  Occurs on Windows/Linux, as @joncatanio suggested, probably a race condition.

Likely hot spots: any place where time is a factor and resource loading, may be elsewhere though.  Checking warnings another good place to start.

**Comment by joncatanio** [comment]
I think I may have isolated this within the camera. It looks like a race condition setting the LA vector, getting input from the mouse etc.

**Comment by rgarmsen2295** [comment]
@joncatanio have you run into this at all or did you fix it? Go ahead and close if so

**Comment by joncatanio** [comment]
Closing this I think it should be fine now.
