### ISSUE TITLE
Better Camera/polling mouse system

### ISSUE THREAD

**Issue by rgarmsen2295** [joncatanio/GrannyGauntlet#7]
Right now the Camera is...half-baked.  Key presses are handled polling style, however, mouse movement is not (currently using static call-backs).  These should be implemented consistently using polling where possible and should use an InputComponent once #8 is done.

**Comment by joncatanio** [comment]
Might not get this one done by the 25% milestone. I haven't decided where to put the mouse polling. I might bake it into the Camera class but it doesn't have an input component, the player does but the player and camera are co-dependent.

**Comment by rgarmsen2295** [comment]
Think you've done this at the 25% level. Will always be iterating and improving however. #26
