### ISSUE TITLE
Fix Blue Screen of Death

### ISSUE THREAD

**Issue by joncatanio** [joncatanio/GrannyGauntlet#80]
Reproduce:
Run `./grannygauntlet` and immediately start moving the mouse/trackpad, you should see a blue screen if you did it fast enough where you were moving the mouse before the window popped up and while it was popping up.

Information:
- It seems to be a GLFW issue
- The problem seems to be in `cursorPositionCallback` found in WindowManager.cpp
- When commenting out the lines:
```
camera.changeAlpha(deltaAlpha);
camera.changeBeta(deltaBeta);
```
the problem seems to go away entirely
- I originally thought it was because the camera was yet to be added to the GameManager thus a race condition was causing calls to garbage data (the camera)
- I moved all of the `cursorPositionCallback` code to PlayerInputComponent.cpp but still had the problem

**Comment by rgarmsen2295** [comment]
Mouse has been disabled, fixed/mitigated for now
